import ScrollToTop from "./components/client/ScrollToTop";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="scroll-smooth">
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
